services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.5.3
    container_name: immich-server
    user: "1000:1000"
    depends_on:
      - immich-redis
      - immich-database
    environment:
      DB_HOSTNAME: immich-database
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      REDIS_HOSTNAME: immich-redis
    volumes:
      - ${DOCKER_DIRECTORY_BASE_PATH}/immich/data:/data
      - ${SERVER_STORAGE_BASE_PATH}/immich:/data/library
      - ${TRANSCODE_BASE_PATH}/immich/upload:/data/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    healthcheck:
      disable: false
    extends:
      file: common.yaml
      service: common
    logging:
      options:
        awslogs-group: /${DEFAULT_BASE_MACHINE}/immich-server

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.3
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${TRANSCODE_BASE_PATH}/immich-machine-learning/model-cache:/cache
    healthcheck:
      disable: false
    extends:
      file: common.yaml
      service: common
    logging:
      options:
        awslogs-group: /${DEFAULT_BASE_MACHINE}/immich-machine-learning

  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    container_name: immich-redis
    healthcheck:
      test: redis-cli ping || exit 1
    extends:
      file: common.yaml
      service: common
    logging:
      options:
        awslogs-group: /${DEFAULT_BASE_MACHINE}/immich-redis

  immich-database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich-postgres
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DOCKER_DIRECTORY_BASE_PATH}/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      disable: false
    shm_size: 128mb
    extends:
      file: common.yaml
      service: common
    logging:
      options:
        awslogs-group: /${DEFAULT_BASE_MACHINE}/immich-database